on: [push]

name: CI

jobs:
  build_and_test:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          docker-compose up -d
          cargo test
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --examples
